name: GolfMinigame
version: '${project.version}'
main: com.chilight.golf.Main
api-version: 1.17
commands:
  minigolf:
    aliases: [golf]

permissions:
  minigolf.reload:
    default: op
    description: Allows you to reload the config